---
title: "My Learning Goals"
description: "A discussion of what I want to get out of E155: Microprocessors"
author: "Jackson Philion"
date: "9/2/24"
categories:
  - reflection
  - labreport
draft: false
---
## Intro – Engineer Of... ?
I remember being a freshman at Harvey Mudd College, living in the room directly across from where I live now as a Senior. I was an aspiring engineer, unsure of what exactly he wanted to actually... engineer. I loved solving problems, but I hadn't yet figured out how I wanted to apply myself. I remembered talking to the engineering seniors in the singles across the hall – some worked on audio amplifiers and processors while others worked on drone tracking or materials research. I listened intently as people talked about their work. I asked a lot of questions, not about the technical details but about the day-to-day work. Around this time as a freshman, I identified my interest in Electrical Engineering. I loved my introductory Computer Science course, but I didn't find it to feel as impactful or tactile as I had hoped. I loved physics, but similarly disliked the lack of immediate applications that I could dream for it. Electrical Engineering seemed to strike a perfect balance. Talking with the seniors, I heard about how they spent time working on their code, working on their hardware, and working in the field to apply their creation – it sounded like the perfect fit. I recalled my internship at Egghead with Tom Morris, where he tasked me with finalizing a plan for a cellular-enabled smart outlet. I remembered the excitement of rigging a power cable through my custom housing, connecting to the 3G network, and seeing the SMD LED first flash solid green. In this newly identified interest, I kept an ear out for courses that the successful electrical engineers at Mudd had all taken. E155: Microprocessors stood out as a clear winner.

## What I Want to Walk Away With

As I approach this course, I recognize it as a capstone of sorts. While I will pursue other electrical courses while at Mudd, perhaps none will provide a greater boost to my electrical expertise. Further, I plan to directly apply these skills as I pursue my sponsored work with HRL Labs for FPGA in quantum computing control systems. So, I want this class to ultimately help me develop into an electrical engineer who is ready to start a career development program in a professional setting. With that said, I hope to:

**1. Gain an understanding of FPGAs and their applications.**

As I hope to develop confidence in my career as an electrical engineer, and understanding of FPGAs seems critical. They are a basic building block of everything from simple embedded systems to high-speed computing at the cutting edge of finance. I want to be capable of sustaining technical conversations with employers and coworkers where I can understand how to apply FPGAs. This means understanding how to break a task into a block diagram, understanding the software and Verilog necessary to implement the task, and most importantly – recognizing the gaps in my knowledge that I need to fill in order to manifest my solution.

**2. Increase my Autonomy (by failing more often).**

An important part of being a team member is understanding when to seek collaboration and when to strike forward for the sake of progress. Increased collaboration may lead to more "correct" results more often, but a dependency on collaboration hinders both your own growth and the efficient progress of the project. Conversely, one might imagine that you can steep-track project progress by focusing on indivual progress. However, this may cause one to lose sight of the project's overall goals and render contributions meaningless. I find that I more often tend to strive for a perfect solution, meaning that I end up checking in often with coworkers to make sure that I am on "the right track". I think I would benefit from increasing my autonomy. In order to do this, I have to be willing to try things and fail more often in smaller pieces. I have to be willing to go out on a (safe) limb and experiment, then bring my results to the group. I believe that this will lead to personal growth, making me a better player on my future team.

## Final Thoughts

While I reserve the right to learn more, these are the essential points that I would be disappointed to leave this class without. These are the points that I think will help me kickstart my career in electrical engineering. I thank Harvey Mudd for putting forth the challenge of this class to its students – I have been excited to take it head on since I was a freshman. I believe that challenges like these are what will push me from student to practicioner, and I can't wait to see the transition take shape. Lab One is already proving to be deceptively simple though not at all easy. So, here we go – Off to the races!